### ISSUE TITLE
SHA-1 cert error on elections.npr.org

### ISSUE THREAD

**Issue by konklone** [nprapps/elections16#148]
The NPR elections site is using HTTPS, which is fantastic, but it's using a weak certificate:

![image](https://cloud.githubusercontent.com/assets/4592/12929511/0e9afd48-cf41-11e5-86f3-e414a05f188a.png)

Specifically, it's using a certificate whose validity relies on the SHA-1 algorithm, an increasingly weak algorithm that browsers and OSes generally intend to remove support for in 2017. Chrome has been [showing aggressive warnings about SHA-1](https://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html) for some time in order to warn site owners about the need to renew certificates.

CAs are all now forbidden from issuing certificates that rely on the SHA-1 algorithm, and so any certificate renewal at all should result in the issue being fixed.

Thanks for using HTTPS, and I hope this is helpful information in improving the site's appearance (and reality) of security for its users.

**Comment by eads** [comment]
Thanks! We are definitely aware of this. We'll fix asap after New
Hampshire; we're a little understaffed at the moment and this requires some
negotiation with other parts of the organization.

On Tue, Feb 9, 2016 at 3:26 PM, Eric Mill notifications@github.com wrote:

> The NPR elections site is using HTTPS, which is fantastic, but it's using
> a weak certificate:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/4592/12929511/0e9afd48-cf41-11e5-86f3-e414a05f188a.png
> 
> Specifically, it's using a certificate whose validity relies on the SHA-1
> algorithm, an increasingly weak algorithm that browsers and OSes generally
> intend to remove support for in 2017. Chrome has been showing aggressive
> warnings about SHA-1
> https://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html
> for some time in order to warn site owners about the need to renew
> certificates.
> 
> CAs are all now forbidden from issuing certificates that rely on the SHA-1
> algorithm, and so any certificate renewal at all should result in the issue
> being fixed.
> 
> Thanks for using HTTPS, and I hope this is helpful information in
> improving the site's appearance (and reality) of security for its users.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nprapps/elections16/issues/148.

## 

David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eads** [comment]
Fix coming next week. Thanks again.

**Comment by konklone** [comment]
No problem, thanks for taking it seriously!

**Comment by eads** [comment]
We had to roll back to regular ol' http in order to handle cross-domain local storage integration with the main npr.org site. When npr.org goes https (some time this year), we'll switch back to https.
